name: global-travel
recipe: drupal9
config:
  webroot: .
  composer_version: 2-latest
services:
  appserver:
    build:
      - composer install
memcached:
  type: memcached
  portforward: false
  mem: 256
excludes: 
  - vendor 
  - node_modules 
  - modules/contrib

